# Generated by Django 3.2 on 2022-01-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_cart', '0002_auto_20220111_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
