# Generated by Django 3.2 on 2022-01-04 22:16

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorsProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', colorfield.fields.ColorField(blank=True, default='', image_field=None, max_length=220, samples=None)),
            ],
        ),
        migrations.CreateModel(
            name='ImageProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='product/image')),
            ],
        ),
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=220)),
                ('main_slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='SizesProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sizes', models.CharField(blank=True, max_length=220)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250)),
                ('description', models.TextField(blank=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, null=True)),
                ('top_or_new', models.CharField(blank=True, choices=[('', ''), ('top', 'top'), ('new', 'new')], default='', max_length=3)),
                ('qty_product', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('color', models.ManyToManyField(blank=True, related_name='color', to='mainapp.ColorsProducts')),
                ('image', models.ManyToManyField(blank=True, to='mainapp.ImageProduct')),
                ('main_category', models.ManyToManyField(blank=True, related_name='main_category', to='mainapp.MainCategory')),
                ('product_category', models.ManyToManyField(blank=True, related_name='product_category', to='mainapp.ProductCategories')),
                ('product_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_user', to=settings.AUTH_USER_MODEL)),
                ('size', models.ManyToManyField(blank=True, related_name='size', to='mainapp.SizesProducts')),
                ('tag', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
