# Generated by Django 4.0.1 on 2022-01-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_category',
            field=models.ManyToManyField(blank=True, db_column='MainCategory_category', related_name='main_category', to='mainapp.MainCategory'),
        ),
    ]
