# Generated by Django 3.2 on 2022-01-24 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qty_product',
        ),
    ]
