# Generated by Django 3.2 on 2022-01-02 06:39

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('address', models.TextField(blank=True)),
                ('comp_tel', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('comp_email', models.EmailField(blank=True, max_length=250)),
                ('weekly', models.CharField(blank=True, max_length=250)),
                ('short_day', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('email', models.ImageField(blank=True, max_length=250, upload_to='')),
                ('phone', phone_field.models.PhoneField(blank=True, max_length=31)),
                ('subject', models.CharField(blank=True, max_length=250)),
                ('message', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='OurBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_address', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(upload_to='contact/branch_image')),
                ('weekly', models.CharField(blank=True, max_length=250)),
                ('short_day', models.CharField(blank=True, max_length=250)),
            ],
        ),
    ]
