# Generated by Django 3.2 on 2022-01-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactinfo_contactuser_ourbranch'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='short_day_time',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='contactinfo',
            name='weekly_time',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
