# Generated by Django 3.2 on 2022-01-02 07:53

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20220102_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='ourbranch',
            name='comp_street',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='ourbranch',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, max_length=31),
        ),
    ]
