# Generated by Django 3.2 on 2022-01-02 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20220102_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ourbranch',
            name='short_day',
            field=models.URLField(blank=True),
        ),
    ]
