# Generated by Django 3.2 on 2021-12-30 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0004_custom_user_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='region',
        ),
    ]
