# Generated by Django 3.2 on 2021-12-29 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='images', to='blog.BlogImages'),
        ),
    ]
