# Generated by Django 3.2 on 2021-12-28 19:24

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adds_News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/about/adds/')),
                ('center', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('our_vision', models.CharField(max_length=100)),
                ('our_vision_full', models.TextField()),
                ('our_mision', models.CharField(max_length=100)),
                ('our_mision_full', models.TextField()),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Add News',
            },
        ),
        migrations.CreateModel(
            name='BrandImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/about/brands/')),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Brand Icons',
                'get_latest_by': ['-date_modified'],
            },
        ),
        migrations.CreateModel(
            name='OurTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(crop=None, force_format='png', keep_meta=True, quality=75, size=[400, 600], upload_to='media/about/our-team/')),
                ('name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('staff', models.CharField(max_length=150)),
                ('about_self', models.CharField(max_length=400)),
                ('facebook_link', models.URLField()),
                ('twetter_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Our Team',
            },
        ),
        migrations.CreateModel(
            name='Brends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=350)),
                ('description', models.CharField(max_length=350)),
                ('date_modified', models.DateTimeField(auto_now=True, null=True)),
                ('date_published', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ManyToManyField(blank=True, related_name='brand_icons', to='about.BrandImage')),
            ],
            options={
                'verbose_name_plural': 'Centre Brand',
            },
        ),
    ]
